// This file is auto-generated by scripts/generate-extra-metadata.ts
// Do not edit manually.

export const EXTRA_METADATA: Record<string, { tags: string[] }> = {
  "M3xnyum4YGs": {
    "tags": [
      "travel",
      "art"
    ]
  },
  "PUwhrmjHKTI": {
    "tags": [
      "travel"
    ]
  },
  "e2wm_VRROvA": {
    "tags": [
      "travel"
    ]
  },
  "zsYDWBsLukQ": {
    "tags": [
      "travel"
    ]
  },
  "RSJF-LpjweY": {
    "tags": [
      "travel"
    ]
  },
  "KvC7BzOh3a4": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "SU1QGhP-pkI": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "6pcEZhk3lSs": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "ADWbVXc69Iw": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "b76G1ZQC-lU": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "x3QXMVbZkcA": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "qU6bxRPltkk": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "xtM7agQLx2o": {
    "tags": [
      "travel"
    ]
  },
  "rjnBQWLnCbI": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "e7oskVv48oY": {
    "tags": [
      "travel",
      "photography"
    ]
  },
  "Kz-yeBNfM7I": {
    "tags": [
      "travel"
    ]
  },
  "OZBBZMKORG4": {
    "tags": [
      "travel",
      "ai"
    ]
  },
  "1jd9QJFFR1E": {
    "tags": [
      "travel",
      "art"
    ]
  },
  "Ate57uZ8_Ck": {
    "tags": [
      "travel",
      "ai"
    ]
  },
  "X_q_4i7rUYU": {
    "tags": [
      "travel"
    ]
  },
  "yeukgKerfqM": {
    "tags": [
      "travel"
    ]
  },
  "kitgsNlUlsY": {
    "tags": [
      "travel"
    ]
  },
  "KaICflreJ0s": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "B9gx7DuyxJk": {
    "tags": [
      "travel",
      "photography"
    ]
  },
  "vMlTeFcIH7M": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "PkaVuvQ6xPs": {
    "tags": [
      "travel"
    ]
  },
  "KJJjJiaLcQ8": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "l__80YNrOAU": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "5HQjR7QkU84": {
    "tags": [
      "travel"
    ]
  },
  "Hn59g-RhkiA": {
    "tags": [
      "travel",
      "ai"
    ]
  },
  "NsnE6b_9ayU": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "8iN6ZoQ2o4Y": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "e53Gpt_QBWo": {
    "tags": [
      "travel"
    ]
  },
  "x3Q7Uw_bgUQ": {
    "tags": [
      "travel"
    ]
  },
  "OVle1yEXL8U": {
    "tags": [
      "travel"
    ]
  },
  "usFnp3mBjWk": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "NQ6_Sqt_w3Y": {
    "tags": [
      "travel"
    ]
  },
  "KqtuK5ybFrg": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "ap8CPtCLWPo": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "1Ba-vS0ZA0E": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "GzMjSi-S7ls": {
    "tags": [
      "travel"
    ]
  },
  "tkjU-5C9avI": {
    "tags": [
      "travel"
    ]
  },
  "5FMB-wjX6yk": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "m0FYJ3s67hg": {
    "tags": [
      "travel",
      "art"
    ]
  },
  "RBJuFF0MF2M": {
    "tags": [
      "travel",
      "ai",
      "photography"
    ]
  },
  "CZ5D8qPMUds": {
    "tags": [
      "travel",
      "ai",
      "lifestyle"
    ]
  },
  "6t0GAP5omF4": {
    "tags": [
      "travel",
      "photography"
    ]
  },
  "ORRIEs44c38": {
    "tags": [
      "travel"
    ]
  },
  "X102VTLr-Kg": {
    "tags": [
      "travel",
      "lifestyle"
    ]
  },
  "aSdyHSV2D0o": {
    "tags": [
      "travel",
      "ai"
    ]
  },
  "37F9l3Q1HzE": {
    "tags": [
      "finance"
    ]
  },
  "7ZHwVk6GuuU": {
    "tags": [
      "finance"
    ]
  },
  "b5BsywkETfU": {
    "tags": [
      "finance"
    ]
  },
  "0m0-1jmfJF4": {
    "tags": [
      "finance"
    ]
  },
  "EyBcps1e38o": {
    "tags": [
      "finance"
    ]
  },
  "DYCroCvPvJU": {
    "tags": [
      "finance"
    ]
  },
  "0GxSnWSp3VM": {
    "tags": [
      "finance"
    ]
  },
  "b_X9JYZKsuI": {
    "tags": [
      "finance"
    ]
  },
  "da5pfEezDjg": {
    "tags": [
      "finance"
    ]
  },
  "RIOcs8stB6w": {
    "tags": [
      "finance"
    ]
  },
  "gY9j79M3AP0": {
    "tags": [
      "finance"
    ]
  },
  "GlDnXpFyie4": {
    "tags": [
      "finance"
    ]
  },
  "rueRn0PLT4c": {
    "tags": [
      "finance"
    ]
  },
  "DobwUfmL-74": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "FweAbACRlb4": {
    "tags": [
      "finance"
    ]
  },
  "QjOvbnu50Gg": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "guBsd2rD2lc": {
    "tags": [
      "finance"
    ]
  },
  "unWPUqnNG4U": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "IKXiyApvKjI": {
    "tags": [
      "finance"
    ]
  },
  "CSxznPhodTk": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "rxWCoHl1atE": {
    "tags": [
      "finance",
      "art"
    ]
  },
  "-rTVgIQubtQ": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "wKSS-3AFVcA": {
    "tags": [
      "finance"
    ]
  },
  "Lhw418kx6u4": {
    "tags": [
      "finance"
    ]
  },
  "E9CXmOxZwDA": {
    "tags": [
      "finance"
    ]
  },
  "hE6xmg9Mmkc": {
    "tags": [
      "cooking"
    ]
  },
  "zPxQjuFoUBc": {
    "tags": [
      "cooking"
    ]
  },
  "18gdBoDT0Rk": {
    "tags": [
      "cooking"
    ]
  },
  "ihbcOF4_2Ok": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "6Db60rwdOuY": {
    "tags": [
      "cooking"
    ]
  },
  "907vZOyWTo8": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "XvSQvWD8MAw": {
    "tags": [
      "cooking"
    ]
  },
  "AdrDNhsh9Iw": {
    "tags": [
      "cooking",
      "ai"
    ]
  },
  "CZliZvnFSv4": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "nCyikFqXViU": {
    "tags": [
      "cooking"
    ]
  },
  "YYsg_vZEDng": {
    "tags": [
      "cooking"
    ]
  },
  "Xao87NNSfiM": {
    "tags": [
      "cooking"
    ]
  },
  "gL_FxHHjz8A": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "qZ-rT0A7MgM": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "3SVi80fjs7U": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "8rTjKu-nm1E": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "rHbtudN5mpI": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "EeuRbuqV_4k": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "kQdasMB4bwc": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "0g8BcjZdW78": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "eqxk2rVPbdA": {
    "tags": [
      "cooking",
      "gadgets"
    ]
  },
  "oDh58oNhJLs": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "86NHFK1RAJ0": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "HrZ5iJ72up0": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "HduytF6T4e4": {
    "tags": [
      "cooking"
    ]
  },
  "6C_xFde9_lc": {
    "tags": [
      "cooking"
    ]
  },
  "qgwHxIXuyvQ": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "jQy39x0l0PE": {
    "tags": [
      "fashion"
    ]
  },
  "EWaHicI-0TY": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "KfkrYaSZv9w": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "m5cYzzHjjKA": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "GZTDYiSWtf0": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "rfYtSoCfmb4": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "yH2EigcECpc": {
    "tags": [
      "cooking"
    ]
  },
  "bgd32MZQCaw": {
    "tags": [
      "cooking",
      "ai"
    ]
  },
  "YHROoIU4LEM": {
    "tags": [
      "cooking"
    ]
  },
  "c6WcA_UGHcQ": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "5oI-qMCZ5dM": {
    "tags": [
      "cooking"
    ]
  },
  "Y_BYBDrbqao": {
    "tags": [
      "cooking"
    ]
  },
  "EQLhVOJedMw": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "J6bSPGorLsA": {
    "tags": [
      "cooking",
      "food",
      "art"
    ]
  },
  "2dR6SzUwbpY": {
    "tags": [
      "cooking"
    ]
  },
  "OAZpSsu03VA": {
    "tags": [
      "cooking"
    ]
  },
  "vr4p_Vp6cxw": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "O27nLt1BRa8": {
    "tags": [
      "cooking"
    ]
  },
  "wvnXL_ycTXQ": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "WJbH04RcOf4": {
    "tags": [
      "cooking"
    ]
  },
  "U-4MCjHtLIs": {
    "tags": [
      "cooking"
    ]
  },
  "lVfNStAU178": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "DfVUf9JeXCI": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "uDhhd4tY7KE": {
    "tags": [
      "cooking",
      "food"
    ]
  },
  "6BvSuOSCrhs": {
    "tags": [
      "gym",
      "ai",
      "fitness"
    ]
  },
  "09wcXpjYlmQ": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "EtGugw_MrOs": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "yPlPACCTXv0": {
    "tags": [
      "finance",
      "art"
    ]
  },
  "iJ0Cczp-E-4": {
    "tags": [
      "finance",
      "ai",
      "art"
    ]
  },
  "WPVXDtdOVrk": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "6EPTegsTCtQ": {
    "tags": [
      "finance"
    ]
  },
  "dxa6DerXU1U": {
    "tags": [
      "finance"
    ]
  },
  "Hhod3AolKqg": {
    "tags": [
      "finance"
    ]
  },
  "mau1GuwfSQs": {
    "tags": [
      "finance"
    ]
  },
  "L3YHVey2WLQ": {
    "tags": [
      "finance"
    ]
  },
  "xQl0YIW28Wo": {
    "tags": [
      "finance",
      "art"
    ]
  },
  "JXBFyIYKu8U": {
    "tags": [
      "finance"
    ]
  },
  "ItxYcK_hjLg": {
    "tags": [
      "finance"
    ]
  },
  "SO42IzoifEg": {
    "tags": [
      "finance"
    ]
  },
  "YrezhjFnC3o": {
    "tags": [
      "finance",
      "art"
    ]
  },
  "TKf9Jc1P3g8": {
    "tags": [
      "finance"
    ]
  },
  "6Fjs9ZU1f1w": {
    "tags": [
      "finance",
      "art"
    ]
  },
  "3rCNaIVG4Tw": {
    "tags": [
      "finance"
    ]
  },
  "dUOpjybSlD8": {
    "tags": [
      "finance"
    ]
  },
  "t1tThCapuiw": {
    "tags": [
      "finance"
    ]
  },
  "NbTXZC-u_SI": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "M1v1ZGUAFi0": {
    "tags": [
      "finance"
    ]
  },
  "iid1URv1wIc": {
    "tags": [
      "finance"
    ]
  },
  "bm_st8OCncA": {
    "tags": [
      "finance"
    ]
  },
  "M4q8c0OF0hY": {
    "tags": [
      "finance"
    ]
  },
  "i7VnK_JD1LM": {
    "tags": [
      "fashion"
    ]
  },
  "XqJTuBN-o70": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "kBlNM4FmG_Q": {
    "tags": [
      "finance",
      "ai"
    ]
  },
  "4zO7i9P8mGE": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "k1WBBa0-fUc": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "rxUm-2x-2dM": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "a2vJLW0ZkX0": {
    "tags": [
      "comedy"
    ]
  },
  "SOnefbe2ZtU": {
    "tags": [
      "comedy",
      "photography"
    ]
  },
  "CdaXTGsMU9A": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "6cXeYfDdxY4": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "JnbVVR_oITI": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "oBv666tN4E4": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "WEX8LSXaHMs": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "B5RlZK7GzQI": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "W56Ve6s06hQ": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "-q88kOTezXk": {
    "tags": [
      "gym"
    ]
  },
  "TSZ7U8re_j0": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "XN6JEH4Sac0": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "oOjuSWoKLws": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "9fAuotkeVsk": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "cyWvb4YgOUA": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "xjrDTiNIQOc": {
    "tags": [
      "gym",
      "ai",
      "fitness"
    ]
  },
  "sr5DqZbuT04": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "EWhMxVsIfPY": {
    "tags": [
      "gym",
      "art"
    ]
  },
  "VHTfvX572R0": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "spQU3c_FUkU": {
    "tags": [
      "gym"
    ]
  },
  "-X3rY91kUX8": {
    "tags": [
      "gym",
      "ai",
      "fitness"
    ]
  },
  "EhDqH4Ggp-k": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "1H6ybczMrZk": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "zaGADl73QHA": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "6V4MSsSoyak": {
    "tags": [
      "gym"
    ]
  },
  "gNrhEse-yrg": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "T8w-kfb9j_E": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "DCpar5QDo6E": {
    "tags": [
      "gym"
    ]
  },
  "qkmHQn7W9to": {
    "tags": [
      "gym"
    ]
  },
  "KPkx5UZfVp0": {
    "tags": [
      "gym"
    ]
  },
  "-NXDt-QBUhs": {
    "tags": [
      "gym",
      "ai",
      "fitness"
    ]
  },
  "ZuEr_YmXI0o": {
    "tags": [
      "gym"
    ]
  },
  "wfJ7O9QiUjg": {
    "tags": [
      "gym"
    ]
  },
  "mUJG782RzNs": {
    "tags": [
      "gym"
    ]
  },
  "ZpG_voAdEX4": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "qC7urbHQLwU": {
    "tags": [
      "gym"
    ]
  },
  "5AW-lgNweWQ": {
    "tags": [
      "gym",
      "ai",
      "fitness"
    ]
  },
  "Icw8KLcpE_Q": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "ieYw7aqx1Es": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "3fTmWgxifxQ": {
    "tags": [
      "gym"
    ]
  },
  "ouKGDXF108U": {
    "tags": [
      "gym",
      "ai",
      "finance"
    ]
  },
  "9fjokv8wYPs": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "RPmFoe8jS0c": {
    "tags": [
      "gym",
      "ai"
    ]
  },
  "p03iq190txc": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "oJ70ZNOlLJg": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "eaPBruNUglE": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "roOWVMDKK4U": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "T5Jw1L0EMPw": {
    "tags": [
      "gym"
    ]
  },
  "hGQeU8NbWDc": {
    "tags": [
      "gym",
      "fitness"
    ]
  },
  "fdyhNhIzb7E": {
    "tags": [
      "gym"
    ]
  },
  "35FmGFRU14w": {
    "tags": [
      "gaming"
    ]
  },
  "VWIOJjj9ij4": {
    "tags": [
      "gaming"
    ]
  },
  "LKcIshYBSOA": {
    "tags": [
      "gaming"
    ]
  },
  "52iN7no-qpE": {
    "tags": [
      "gaming"
    ]
  },
  "o8q7auLARMQ": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "A9NwucYYzl4": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "FeN7zcEnk-A": {
    "tags": [
      "gaming"
    ]
  },
  "1VeG0FqkLR4": {
    "tags": [
      "gaming"
    ]
  },
  "K5Wl-6wIuA8": {
    "tags": [
      "gaming"
    ]
  },
  "nwDDdqp8xv8": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "K0QJnxaQ-yM": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "ereqEhSp3Xc": {
    "tags": [
      "gaming"
    ]
  },
  "bLoj92RJ-Ds": {
    "tags": [
      "gaming"
    ]
  },
  "2A5piB0QgwE": {
    "tags": [
      "gaming"
    ]
  },
  "izYpcgUvdfo": {
    "tags": [
      "gaming"
    ]
  },
  "nvvVeiLYzwg": {
    "tags": [
      "gaming"
    ]
  },
  "I7r36SaWUtk": {
    "tags": [
      "gaming"
    ]
  },
  "2YCv_9IaQw8": {
    "tags": [
      "gaming"
    ]
  },
  "lHzmQaQ9tbA": {
    "tags": [
      "gaming"
    ]
  },
  "OngyJg9-kSA": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "PsnrXc5taUo": {
    "tags": [
      "gaming"
    ]
  },
  "OfFWYSc5Hzo": {
    "tags": [
      "gaming"
    ]
  },
  "YJIkxKCiQMQ": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "zhcoaSUnCX4": {
    "tags": [
      "gaming"
    ]
  },
  "ClrfV16V3Wg": {
    "tags": [
      "gaming"
    ]
  },
  "gsTVNEAzCTc": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "eVb1w1DYWwQ": {
    "tags": [
      "gaming"
    ]
  },
  "Lf9U7g6J_ow": {
    "tags": [
      "gaming"
    ]
  },
  "9a4FQIfXVSs": {
    "tags": [
      "gaming"
    ]
  },
  "itYYDeDKU9M": {
    "tags": [
      "gaming"
    ]
  },
  "x45N8Ar-0hA": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "iZISIzM2haw": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "tmvYRXyMYJQ": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "8CmWHuGqOJg": {
    "tags": [
      "gaming",
      "art"
    ]
  },
  "0pRmIBD89Sk": {
    "tags": [
      "gaming"
    ]
  },
  "9ZBaFbt1-OQ": {
    "tags": [
      "gaming"
    ]
  },
  "KqIkIacxgRo": {
    "tags": [
      "gaming"
    ]
  },
  "N4giAc4BH1s": {
    "tags": [
      "gaming"
    ]
  },
  "sV1SS09C-Bs": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "DktqTctE3h4": {
    "tags": [
      "gaming"
    ]
  },
  "7W7fWs7FpYc": {
    "tags": [
      "gaming"
    ]
  },
  "-txyYKsK4eg": {
    "tags": [
      "gaming"
    ]
  },
  "0UtiKVlm4XY": {
    "tags": [
      "gaming"
    ]
  },
  "KQIpqFblvMI": {
    "tags": [
      "gaming"
    ]
  },
  "ly61nZKVJYs": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "VAqHEP-bSu0": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "yvnZ3P6afiw": {
    "tags": [
      "gaming"
    ]
  },
  "RqRBw8wHUso": {
    "tags": [
      "gaming"
    ]
  },
  "CCNT2J0NYmY": {
    "tags": [
      "gaming",
      "ai"
    ]
  },
  "st1TjbIAMGY": {
    "tags": [
      "gaming"
    ]
  },
  "3punW8R-OBQ": {
    "tags": [
      "beauty"
    ]
  },
  "raEnFm0sdnc": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "48CWj2I3cf0": {
    "tags": [
      "beauty"
    ]
  },
  "hNoS2BU6bbQ": {
    "tags": [
      "comedy"
    ]
  },
  "sxmTTS4qros": {
    "tags": [
      "comedy"
    ]
  },
  "yF4QodSHgL8": {
    "tags": [
      "comedy"
    ]
  },
  "u8Kt7fRa2Wc": {
    "tags": [
      "comedy"
    ]
  },
  "qupyKBVmwQc": {
    "tags": [
      "comedy"
    ]
  },
  "v_b_COFRnjo": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "tyeQVjAPx_I": {
    "tags": [
      "comedy"
    ]
  },
  "a8_d_IhsBJg": {
    "tags": [
      "comedy"
    ]
  },
  "JlXNGprnjYs": {
    "tags": [
      "comedy"
    ]
  },
  "ZOzzRlc_qho": {
    "tags": [
      "comedy"
    ]
  },
  "x8S2D8gi4ts": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "KV1e4ooMIX0": {
    "tags": [
      "comedy"
    ]
  },
  "erLTOojf9_I": {
    "tags": [
      "comedy"
    ]
  },
  "ZkpG5eklE0I": {
    "tags": [
      "comedy"
    ]
  },
  "pv3WYwaZVg0": {
    "tags": [
      "comedy"
    ]
  },
  "SXiG4hjvrBo": {
    "tags": [
      "comedy"
    ]
  },
  "MuoyTLlw0Yc": {
    "tags": [
      "comedy"
    ]
  },
  "ZhgZyH_3V2s": {
    "tags": [
      "beauty",
      "fashion"
    ]
  },
  "cUpR1z2fge0": {
    "tags": [
      "comedy"
    ]
  },
  "mokllJ_Sz_g": {
    "tags": [
      "comedy"
    ]
  },
  "bLCkiVTnLqw": {
    "tags": [
      "comedy"
    ]
  },
  "N4z5YRdjJQ4": {
    "tags": [
      "comedy"
    ]
  },
  "xFu_Xx_LSKo": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "uPixeRzq468": {
    "tags": [
      "comedy"
    ]
  },
  "vkmZMz9gxVc": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "ED0NKBVy0fA": {
    "tags": [
      "comedy"
    ]
  },
  "lwlJmwsG8Kw": {
    "tags": [
      "comedy"
    ]
  },
  "B14PQpPVyqs": {
    "tags": [
      "comedy"
    ]
  },
  "4qQtqpwNnLE": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "v-LY0Td8y0A": {
    "tags": [
      "comedy"
    ]
  },
  "rZnrHfuENQY": {
    "tags": [
      "comedy"
    ]
  },
  "QAWnec3oW70": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "rQ36tBDPONI": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "KcKEzT2dAZ8": {
    "tags": [
      "comedy",
      "ai"
    ]
  },
  "DzDHhKNB3j8": {
    "tags": [
      "comedy"
    ]
  },
  "w836h2c61XM": {
    "tags": [
      "comedy"
    ]
  },
  "6d8g9vSOiTA": {
    "tags": [
      "comedy"
    ]
  },
  "qEQhziwFTcU": {
    "tags": [
      "comedy"
    ]
  },
  "Th1lwaDNZdg": {
    "tags": [
      "comedy"
    ]
  },
  "KA8leh1hikQ": {
    "tags": [
      "comedy",
      "art"
    ]
  },
  "XBcuJ-zeSF4": {
    "tags": [
      "comedy"
    ]
  },
  "m7TwCdB5Yxw": {
    "tags": [
      "comedy"
    ]
  },
  "ivFGReq8eGE": {
    "tags": [
      "comedy"
    ]
  },
  "73VpmWdR26k": {
    "tags": [
      "comedy"
    ]
  },
  "2ZFgD9fbnb8": {
    "tags": [
      "comedy"
    ]
  },
  "h73JDioDTO8": {
    "tags": [
      "music"
    ]
  },
  "LB-jPGnR9Ok": {
    "tags": [
      "music"
    ]
  },
  "5My4eQCH_1M": {
    "tags": [
      "music"
    ]
  },
  "ouZ8Ap8JUMQ": {
    "tags": [
      "music"
    ]
  },
  "qNacTIWh22E": {
    "tags": [
      "music"
    ]
  },
  "53Qzi9gqbTE": {
    "tags": [
      "music"
    ]
  },
  "gsnG2TPZfz8": {
    "tags": [
      "music"
    ]
  },
  "pCTrZR0YMuE": {
    "tags": [
      "music"
    ]
  },
  "uCp8mfr_1MI": {
    "tags": [
      "music"
    ]
  },
  "4uv6VFFTE6g": {
    "tags": [
      "music"
    ]
  },
  "jutZ68bTXS4": {
    "tags": [
      "music"
    ]
  },
  "S9QfNa8ZncQ": {
    "tags": [
      "music",
      "art"
    ]
  },
  "8X6iZ58Ls2M": {
    "tags": [
      "music"
    ]
  },
  "MkdqimvLDiQ": {
    "tags": [
      "music"
    ]
  },
  "4kDV1vPZ_UI": {
    "tags": [
      "music"
    ]
  },
  "4b0-SRoSXfs": {
    "tags": [
      "music"
    ]
  },
  "f11aeGIxGrY": {
    "tags": [
      "music"
    ]
  },
  "hquxopnIzyQ": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "sFBfcH0SWuA": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "dB8g_3N5r8U": {
    "tags": [
      "music"
    ]
  },
  "5SyYnWGSemY": {
    "tags": [
      "music"
    ]
  },
  "7ZBki9DoJls": {
    "tags": [
      "music"
    ]
  },
  "o0JHGmKPfT8": {
    "tags": [
      "music"
    ]
  },
  "XcdJVFn_E2w": {
    "tags": [
      "music"
    ]
  },
  "ZLt1QmlRW2A": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "mctAD2CJPVA": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "PJ2-5Qh1JNs": {
    "tags": [
      "music",
      "art"
    ]
  },
  "6ylqy077XFo": {
    "tags": [
      "music"
    ]
  },
  "X34bjKhjzto": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "wyR5Zg6m9bc": {
    "tags": [
      "music"
    ]
  },
  "M3hRFnMbh_M": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "hFK_UblQSQk": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "CNuMtv4ryL8": {
    "tags": [
      "music"
    ]
  },
  "YKXM43ezodo": {
    "tags": [
      "music",
      "ai",
      "art"
    ]
  },
  "gP1paIlfhMI": {
    "tags": [
      "music",
      "art"
    ]
  },
  "zCd1cbG95Vg": {
    "tags": [
      "music"
    ]
  },
  "qbJg-sIP3L4": {
    "tags": [
      "music"
    ]
  },
  "E0PJ3QJKRvE": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "tVUYghhiBuQ": {
    "tags": [
      "music"
    ]
  },
  "sQL_sdJJej0": {
    "tags": [
      "music"
    ]
  },
  "kQv25HYqwpM": {
    "tags": [
      "music"
    ]
  },
  "8QLzqcZdHCg": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "amRmfrPMES4": {
    "tags": [
      "music"
    ]
  },
  "sB3UfUzhHxg": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "hbstT1uZpQw": {
    "tags": [
      "beauty",
      "ai"
    ]
  },
  "XqUCuTaLiEY": {
    "tags": [
      "beauty"
    ]
  },
  "bzSApOX8184": {
    "tags": [
      "beauty"
    ]
  },
  "tHiuBDhAOkQ": {
    "tags": [
      "beauty"
    ]
  },
  "ZHCbdaU-5tg": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "TdPoPLmTCvE": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "qDLzxVfMKWo": {
    "tags": [
      "beauty"
    ]
  },
  "EpE66elqo9Q": {
    "tags": [
      "beauty"
    ]
  },
  "zDCyeDQYvzI": {
    "tags": [
      "beauty"
    ]
  },
  "5LvI-MUbg6E": {
    "tags": [
      "beauty"
    ]
  },
  "GpxLhVepz-s": {
    "tags": [
      "beauty"
    ]
  },
  "0qYeVIvHEY4": {
    "tags": [
      "beauty"
    ]
  },
  "aGW7g9_CHR4": {
    "tags": [
      "beauty"
    ]
  },
  "shnaNKqraO0": {
    "tags": [
      "beauty"
    ]
  },
  "6E1W3Vj6X6s": {
    "tags": [
      "beauty"
    ]
  },
  "AvlRvFlme-w": {
    "tags": [
      "beauty"
    ]
  },
  "H9yg-c4i_Fg": {
    "tags": [
      "beauty"
    ]
  },
  "EAQuBepUxJw": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "_BQ_wTxrGo4": {
    "tags": [
      "beauty"
    ]
  },
  "77ne9WC-i5M": {
    "tags": [
      "beauty"
    ]
  },
  "GdYvEpV3Sec": {
    "tags": [
      "beauty"
    ]
  },
  "i9dNa9WHNno": {
    "tags": [
      "beauty"
    ]
  },
  "tjWUN0rMs2E": {
    "tags": [
      "beauty"
    ]
  },
  "CsQnTIwr2pw": {
    "tags": [
      "beauty"
    ]
  },
  "ZuvgNdVQFGc": {
    "tags": [
      "beauty",
      "ai"
    ]
  },
  "7BaqKJ3tuHY": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "EWBE7wN2pVk": {
    "tags": [
      "beauty"
    ]
  },
  "bQoLI_SXOLE": {
    "tags": [
      "beauty"
    ]
  },
  "1dwXXDHi6YU": {
    "tags": [
      "music"
    ]
  },
  "Wq2z3nh2weU": {
    "tags": [
      "beauty",
      "ai"
    ]
  },
  "7G4SWkZJ7gI": {
    "tags": [
      "beauty"
    ]
  },
  "QPyAc0MFItI": {
    "tags": [
      "beauty"
    ]
  },
  "mIQWksvErCQ": {
    "tags": [
      "beauty"
    ]
  },
  "xGrQi_7Lz38": {
    "tags": [
      "beauty"
    ]
  },
  "EiPKvmCeg9Y": {
    "tags": [
      "beauty"
    ]
  },
  "G-pYpVdAcLM": {
    "tags": [
      "beauty"
    ]
  },
  "umxtCDTaxDg": {
    "tags": [
      "beauty",
      "ai",
      "art"
    ]
  },
  "Vkgtd-0iQN8": {
    "tags": [
      "beauty"
    ]
  },
  "MLX4kwT15_E": {
    "tags": [
      "beauty",
      "art"
    ]
  },
  "_c7_fGfXMPE": {
    "tags": [
      "beauty"
    ]
  },
  "6aw5uxpJQqk": {
    "tags": [
      "beauty"
    ]
  },
  "XwD0DjOLJwc": {
    "tags": [
      "beauty",
      "ai"
    ]
  },
  "uw4H3T3gZ94": {
    "tags": [
      "beauty"
    ]
  },
  "aAGnEkeWLS8": {
    "tags": [
      "beauty"
    ]
  },
  "aY5Esbjci80": {
    "tags": [
      "beauty"
    ]
  },
  "4sKQxdamwTM": {
    "tags": [
      "beauty"
    ]
  },
  "gDtV_hc1lmQ": {
    "tags": [
      "beauty"
    ]
  },
  "3NNKgSPrTNI": {
    "tags": [
      "music",
      "ai"
    ]
  },
  "QnsE--9dVy0": {
    "tags": [
      "music"
    ]
  },
  "Tsbh0jRjXvg": {
    "tags": [
      "music"
    ]
  },
  "JZWQv4kFJJg": {
    "tags": [
      "music"
    ]
  },
  "O411Zgxo-vY": {
    "tags": [
      "music"
    ]
  },
  "_ugoxztLc5Q": {
    "tags": [
      "fashion"
    ]
  },
  "ThligBzaFJk": {
    "tags": [
      "fashion",
      "art"
    ]
  },
  "xz1X2EqM6Io": {
    "tags": [
      "fashion"
    ]
  },
  "HhgxUnlhG4M": {
    "tags": [
      "fashion"
    ]
  },
  "Pstz0DD4gwI": {
    "tags": [
      "fashion"
    ]
  },
  "r7k3wbaQU5s": {
    "tags": [
      "fashion"
    ]
  },
  "nwsL8PpqBqY": {
    "tags": [
      "fashion"
    ]
  },
  "1SlspKgd0Pc": {
    "tags": [
      "fashion"
    ]
  },
  "Wtv6CVXk0Bk": {
    "tags": [
      "fashion"
    ]
  },
  "aFVOoUvWgw4": {
    "tags": [
      "fashion"
    ]
  },
  "9sQ1rGrj3_s": {
    "tags": [
      "fashion"
    ]
  },
  "5QZlMcZ9Xxw": {
    "tags": [
      "fashion",
      "lifestyle"
    ]
  },
  "uyRsjwnTYVs": {
    "tags": [
      "fashion"
    ]
  },
  "ytiXH4zSJpY": {
    "tags": [
      "fashion"
    ]
  },
  "TUu0vlMtnuQ": {
    "tags": [
      "fashion"
    ]
  },
  "8GRFfM7fxT8": {
    "tags": [
      "fashion"
    ]
  },
  "WnM_-V1GMXc": {
    "tags": [
      "fashion"
    ]
  },
  "5313ip2watA": {
    "tags": [
      "fashion"
    ]
  },
  "pZIiVkukMbk": {
    "tags": [
      "fashion"
    ]
  },
  "XwjjWyNAG2o": {
    "tags": [
      "fashion",
      "art"
    ]
  },
  "QeXrLkOqFdw": {
    "tags": [
      "fashion"
    ]
  },
  "z_bs9m2eLC4": {
    "tags": [
      "fashion"
    ]
  },
  "jH6hKSF4SRk": {
    "tags": [
      "fashion"
    ]
  },
  "xhH8JYcjP-U": {
    "tags": [
      "fashion"
    ]
  },
  "7oFDnDGv6GU": {
    "tags": [
      "fashion"
    ]
  },
  "TpPVQ_IotVg": {
    "tags": [
      "fashion"
    ]
  },
  "XW7vyRTu618": {
    "tags": [
      "fashion"
    ]
  },
  "u7WFDbR0Bu0": {
    "tags": [
      "fashion",
      "ai"
    ]
  },
  "XWMtpCKtAQc": {
    "tags": [
      "fashion"
    ]
  },
  "dVZnEoxWv9M": {
    "tags": [
      "fashion"
    ]
  },
  "Rrf57Znm5xg": {
    "tags": [
      "fashion",
      "art"
    ]
  },
  "A4DUvUfhm0s": {
    "tags": [
      "fashion"
    ]
  },
  "cXlfAbFvknA": {
    "tags": [
      "fashion"
    ]
  },
  "ZpQgfiNYj_Q": {
    "tags": [
      "fashion",
      "ai"
    ]
  },
  "tPDLLAXe4hg": {
    "tags": [
      "fashion"
    ]
  },
  "WmOPLzf1qpg": {
    "tags": [
      "fashion"
    ]
  },
  "YEd3A905dRM": {
    "tags": [
      "fashion"
    ]
  },
  "JV2qYzAVbSc": {
    "tags": [
      "fashion"
    ]
  },
  "QR4Gm7kNPag": {
    "tags": [
      "fashion"
    ]
  },
  "vnrnozxyMe4": {
    "tags": [
      "fashion"
    ]
  },
  "Mble0zoK16Y": {
    "tags": [
      "fashion",
      "art"
    ]
  },
  "iXPUlIDeo64": {
    "tags": [
      "fashion"
    ]
  },
  "XEgF8YVYhOI": {
    "tags": [
      "fashion"
    ]
  },
  "TlIkVwVK3Gw": {
    "tags": [
      "fashion"
    ]
  },
  "JNfmmwXXHhU": {
    "tags": [
      "fashion"
    ]
  },
  "uD4QSpK8CI4": {
    "tags": [
      "fashion"
    ]
  },
  "zHcq37WiNMg": {
    "tags": [
      "fashion"
    ]
  },
  "W9yTv-TLyw4": {
    "tags": [
      "fashion"
    ]
  },
  "DhN4B8J3HzA": {
    "tags": [
      "dance"
    ]
  },
  "HxSvxyEHjRM": {
    "tags": [
      "dance",
      "music"
    ]
  },
  "z7-yoZ4Ofk0": {
    "tags": [
      "dance"
    ]
  },
  "XGtUNS57-XU": {
    "tags": [
      "dance"
    ]
  },
  "aYgA6cIzqm8": {
    "tags": [
      "dance",
      "music"
    ]
  },
  "9CRB8FTsErs": {
    "tags": [
      "dance"
    ]
  },
  "yHo6G3SmEIM": {
    "tags": [
      "dance"
    ]
  },
  "-uZXbOzshe4": {
    "tags": [
      "dance"
    ]
  },
  "qdZZGsp2szI": {
    "tags": [
      "dance"
    ]
  },
  "kwCcR7tgZb8": {
    "tags": [
      "dance"
    ]
  },
  "FQbgQr2Uz-8": {
    "tags": [
      "dance"
    ]
  },
  "SdUS6f4g_O4": {
    "tags": [
      "dance"
    ]
  },
  "Pts30_DGaxw": {
    "tags": [
      "dance"
    ]
  },
  "qgwDfUbwGnQ": {
    "tags": [
      "dance"
    ]
  },
  "VxEmLfoAt4o": {
    "tags": [
      "dance"
    ]
  },
  "iuRlNI9lBuE": {
    "tags": [
      "dance"
    ]
  },
  "zog5V4nn0aw": {
    "tags": [
      "dance"
    ]
  },
  "G_MFAhyhino": {
    "tags": [
      "dance",
      "ai"
    ]
  },
  "4ar4bwuJwLo": {
    "tags": [
      "dance"
    ]
  },
  "lH7hZW6AjsI": {
    "tags": [
      "dance"
    ]
  },
  "XEKplo3xcq8": {
    "tags": [
      "dance"
    ]
  },
  "rc8oEd6bIfQ": {
    "tags": [
      "dance"
    ]
  },
  "d0A6TAyqG7I": {
    "tags": [
      "dance"
    ]
  },
  "Kj7KHmInL5U": {
    "tags": [
      "dance"
    ]
  },
  "KdAtGO4KjeQ": {
    "tags": [
      "dance"
    ]
  },
  "FlM69HIU8xM": {
    "tags": [
      "dance",
      "ai"
    ]
  },
  "majSL-P86EQ": {
    "tags": [
      "dance"
    ]
  },
  "jUjaOqdNOw4": {
    "tags": [
      "dance"
    ]
  },
  "o2amXB3yVWw": {
    "tags": [
      "dance",
      "art"
    ]
  },
  "UYf0TDdKewQ": {
    "tags": [
      "dance"
    ]
  },
  "oc67fM-AeOA": {
    "tags": [
      "dance",
      "ai"
    ]
  },
  "luFyVrB8NuE": {
    "tags": [
      "sports"
    ]
  },
  "pu8Qd2nJCjw": {
    "tags": [
      "dance"
    ]
  },
  "2tYi0xf6n3Y": {
    "tags": [
      "dance"
    ]
  },
  "vOBE3oqdVoo": {
    "tags": [
      "dance"
    ]
  },
  "_PzBQ0EmjN8": {
    "tags": [
      "dance"
    ]
  },
  "JAeVcLPP8kI": {
    "tags": [
      "dance"
    ]
  },
  "w5cZM23PG-k": {
    "tags": [
      "dance"
    ]
  },
  "8PvRGqD6Nk8": {
    "tags": [
      "dance"
    ]
  },
  "8L-r6WlDbNA": {
    "tags": [
      "dance"
    ]
  },
  "H54GdgTKMtM": {
    "tags": [
      "dance"
    ]
  },
  "4KZa5QrrlrA": {
    "tags": [
      "dance",
      "art"
    ]
  },
  "58e5S064K8I": {
    "tags": [
      "dance"
    ]
  },
  "pracm1xsMDo": {
    "tags": [
      "dance"
    ]
  },
  "CL7Xp7bJi5E": {
    "tags": [
      "dance"
    ]
  },
  "9ddc8Lto8cA": {
    "tags": [
      "dance"
    ]
  },
  "RUj8kFde0o8": {
    "tags": [
      "dance",
      "ai"
    ]
  },
  "3pxeZSTHoq8": {
    "tags": [
      "dance"
    ]
  },
  "dNRJ8Z_PXDI": {
    "tags": [
      "dance",
      "ai"
    ]
  },
  "dmeSjBBWR2s": {
    "tags": [
      "dance"
    ]
  },
  "5FPRfo0tkhM": {
    "tags": [
      "dance"
    ]
  },
  "8Rx0YvNMwrY": {
    "tags": [
      "sports"
    ]
  },
  "O5BC-YOwzig": {
    "tags": [
      "sports"
    ]
  },
  "T4zN_5hlsq8": {
    "tags": [
      "sports"
    ]
  },
  "lURc-s9RYVo": {
    "tags": [
      "sports"
    ]
  },
  "N4LepUcp9zo": {
    "tags": [
      "sports"
    ]
  },
  "CPvoejF9k2o": {
    "tags": [
      "sports"
    ]
  },
  "vBGd4COy8BY": {
    "tags": [
      "sports"
    ]
  },
  "_uqGrTXwY20": {
    "tags": [
      "sports",
      "ai",
      "music"
    ]
  },
  "X9-lz2l2DsA": {
    "tags": [
      "sports"
    ]
  },
  "oeG3pG_Jfuk": {
    "tags": [
      "sports"
    ]
  },
  "wI5sGCDkBvY": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "15DROweeVBU": {
    "tags": [
      "sports"
    ]
  },
  "BWV1f3Y-J9U": {
    "tags": [
      "sports"
    ]
  },
  "elGUGhLTQE8": {
    "tags": [
      "sports",
      "photography"
    ]
  },
  "eICRI306LkU": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "qWAQ4jy9sbg": {
    "tags": [
      "sports"
    ]
  },
  "K8UxsN6MlB0": {
    "tags": [
      "sports"
    ]
  },
  "zA7MviuNJ-8": {
    "tags": [
      "sports"
    ]
  },
  "MP7Ea9qdBto": {
    "tags": [
      "sports"
    ]
  },
  "IkPgY3-gnPM": {
    "tags": [
      "sports"
    ]
  },
  "JzgVOFb7sq0": {
    "tags": [
      "sports"
    ]
  },
  "EiAPJr9U_q4": {
    "tags": [
      "sports"
    ]
  },
  "w-Fv88-_D3w": {
    "tags": [
      "sports"
    ]
  },
  "-8wdpqqXBiE": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "eTGDDaK3kK0": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "dwpKqV301h0": {
    "tags": [
      "sports"
    ]
  },
  "Dj2jioqD-Hw": {
    "tags": [
      "sports"
    ]
  },
  "sz-GWm0u4ME": {
    "tags": [
      "diy"
    ]
  },
  "aHPpsQbuLQQ": {
    "tags": [
      "sports"
    ]
  },
  "oz3onQGlVvU": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "ZfelKipbJ4Y": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "J9i5bvMcgeY": {
    "tags": [
      "sports",
      "ai"
    ]
  },
  "2qjaZgDIh78": {
    "tags": [
      "sports"
    ]
  },
  "Wfw6TFpGwUg": {
    "tags": [
      "sports"
    ]
  },
  "hKzDVTPpj08": {
    "tags": [
      "sports"
    ]
  },
  "yiLzznybxs8": {
    "tags": [
      "sports"
    ]
  },
  "UvcWSOQjiG4": {
    "tags": [
      "sports"
    ]
  },
  "nCjUBkmrB60": {
    "tags": [
      "sports"
    ]
  },
  "OqOHNCGFbVQ": {
    "tags": [
      "sports"
    ]
  },
  "Uzjij9RPeZs": {
    "tags": [
      "sports"
    ]
  },
  "D09QkQ8Cyow": {
    "tags": [
      "sports"
    ]
  },
  "_9VmZhJI6fs": {
    "tags": [
      "sports"
    ]
  },
  "TAdpwMv-tmM": {
    "tags": [
      "sports"
    ]
  },
  "HzZGq97GW94": {
    "tags": [
      "sports"
    ]
  },
  "e49zckdI548": {
    "tags": [
      "sports"
    ]
  },
  "9TKxHUqWAo4": {
    "tags": [
      "pets"
    ]
  },
  "w6y0mxkZVp0": {
    "tags": [
      "pets"
    ]
  },
  "rc0TEvLeOyA": {
    "tags": [
      "pets"
    ]
  },
  "6Zas6BBFk7w": {
    "tags": [
      "pets",
      "ai",
      "photography"
    ]
  },
  "z4OC3pYuOUw": {
    "tags": [
      "pets"
    ]
  },
  "2tPLJ1gsLvU": {
    "tags": [
      "pets",
      "art"
    ]
  },
  "d2jPd-JPg6g": {
    "tags": [
      "pets",
      "art"
    ]
  },
  "-TjojsxYU6U": {
    "tags": [
      "pets"
    ]
  },
  "mxPDp1esjE4": {
    "tags": [
      "pets"
    ]
  },
  "j1bP08fooHE": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "vEptiF_dXHg": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "9ZQqPks_APk": {
    "tags": [
      "pets"
    ]
  },
  "1tojp2IwOXA": {
    "tags": [
      "pets"
    ]
  },
  "3i_bPtf2PuQ": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "lwWhOvfM2wY": {
    "tags": [
      "pets",
      "art"
    ]
  },
  "N88hXQ4KOOs": {
    "tags": [
      "pets"
    ]
  },
  "hdqiKf6yubA": {
    "tags": [
      "pets"
    ]
  },
  "fnO0EYi-skQ": {
    "tags": [
      "pets"
    ]
  },
  "dioC4sSuJUE": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "Hh0WJ18fut8": {
    "tags": [
      "pets"
    ]
  },
  "r4so4HehWnY": {
    "tags": [
      "pets"
    ]
  },
  "ih7q2SE5M18": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "UbJAS3Ge3yE": {
    "tags": [
      "pets"
    ]
  },
  "F3qE951zzqA": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "p4AGbTnsxs8": {
    "tags": [
      "pets",
      "ai",
      "art"
    ]
  },
  "yBfSAzM-S0E": {
    "tags": [
      "pets"
    ]
  },
  "Mgbgeyz4fPE": {
    "tags": [
      "pets"
    ]
  },
  "S_mZNjrtLqs": {
    "tags": [
      "pets"
    ]
  },
  "tN6E06lnb3E": {
    "tags": [
      "pets"
    ]
  },
  "s6En5BSgRZQ": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "EM41yq0OUQ4": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "XkwS5l157GA": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "byeYjhNr_no": {
    "tags": [
      "pets"
    ]
  },
  "Po098TRdOn4": {
    "tags": [
      "pets"
    ]
  },
  "txwgIb64Gf0": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "mCNoYY8-8es": {
    "tags": [
      "pets"
    ]
  },
  "OYdvEVgFEQ0": {
    "tags": [
      "pets"
    ]
  },
  "BKocnHls9XI": {
    "tags": [
      "pets"
    ]
  },
  "76W1ZtZfgFk": {
    "tags": [
      "pets"
    ]
  },
  "YoRE6wJIIwc": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "IZMbqcn2wR8": {
    "tags": [
      "pets",
      "art"
    ]
  },
  "HCYYD1bmldo": {
    "tags": [
      "pets"
    ]
  },
  "1RZGofrWcgE": {
    "tags": [
      "pets"
    ]
  },
  "q-Ko7wdglqo": {
    "tags": [
      "pets"
    ]
  },
  "y8pGG1zZKa4": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "7SdcKbUI414": {
    "tags": [
      "pets",
      "ai"
    ]
  },
  "QOM_uUH75r4": {
    "tags": [
      "pets"
    ]
  },
  "LHRaPXGx_qw": {
    "tags": [
      "pets"
    ]
  },
  "p4Jj9QZFJvw": {
    "tags": [
      "pets"
    ]
  },
  "mtQzK4bZobA": {
    "tags": [
      "pets"
    ]
  },
  "VSQH59v0-Xw": {
    "tags": [
      "diy"
    ]
  },
  "NULMtLBDBWU": {
    "tags": [
      "diy"
    ]
  },
  "gmBUzsNBJ7g": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "-luxTOd8y6Y": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "4-nZCJoP2h0": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "E97Xno9MVBs": {
    "tags": [
      "diy"
    ]
  },
  "_ZG9zQmFTQ4": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "VTFvTq0Ke2Q": {
    "tags": [
      "diy"
    ]
  },
  "Ud5_j9m74es": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "68wU4YwKo90": {
    "tags": [
      "diy",
      "ai"
    ]
  },
  "Ew_R_0xntVc": {
    "tags": [
      "diy"
    ]
  },
  "sJUVzMb6Bg0": {
    "tags": [
      "diy"
    ]
  },
  "Y5fQ7ws9Lnc": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "QTwP1PHL4hI": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "D7nrq1QT7hk": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "o2yB6oOqyIE": {
    "tags": [
      "diy"
    ]
  },
  "UpLM8K-GhiA": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "x5pPPk6mrvU": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "0oFX83UyXco": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "72A0NkrSpdo": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "6vS6hn18Q8w": {
    "tags": [
      "diy",
      "ai"
    ]
  },
  "hnX7eqQNTjs": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "d2uwBQ1T21g": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "R2ZGMo7ZI-I": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "HaiAbOJHl7Y": {
    "tags": [
      "diy"
    ]
  },
  "S1JQ3-VLr0E": {
    "tags": [
      "diy"
    ]
  },
  "Bc2h4XNrBIo": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "hl09_DWn-Lk": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "jE5vrWsA2JE": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "FwZ7djQTjaY": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "8sQks7bLfEE": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "t1vIMqPCyJo": {
    "tags": [
      "diy",
      "ai"
    ]
  },
  "obhJOvatVa0": {
    "tags": [
      "diy"
    ]
  },
  "alYm_Jx-eRE": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "9GDsH1EdQqw": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "VjUvh5EFhDY": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "IGgu75HInrw": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "3pXpwAFfWX8": {
    "tags": [
      "diy"
    ]
  },
  "dvHMHCRGudM": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "OtowNGQPiVo": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "Wl7teXBWziU": {
    "tags": [
      "diy"
    ]
  },
  "BFmHI7-WX1o": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "YR9SEGxzk44": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "ybx5ABnrh0w": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "OEWtQLQ9czs": {
    "tags": [
      "diy"
    ]
  },
  "cPM7APE4XSQ": {
    "tags": [
      "diy",
      "ai",
      "art"
    ]
  },
  "vKVH5mhb0vs": {
    "tags": [
      "diy"
    ]
  },
  "6Fcd0F8pUEQ": {
    "tags": [
      "diy",
      "art"
    ]
  },
  "WMSXxzpT0Jw": {
    "tags": [
      "diy"
    ]
  },
  "mkcgVN90zl0": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "LZYfSYXY-go": {
    "tags": [
      "tech",
      "apple",
      "gadgets"
    ]
  },
  "4wZwXhoxRIA": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "egunzY77ZdQ": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "uuJ14E73kqE": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "iqcT0qOuPlE": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "9C4rAMQlUiE": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "gsJAlLOFBv0": {
    "tags": [
      "tech"
    ]
  },
  "Lb4FScsL1Tw": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "h1d3XTXOFdg": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "hub3VypXV70": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "efemIGFQ64M": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "wCjHZoo1Iz8": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "XBSTOfjc5nY": {
    "tags": [
      "tech"
    ]
  },
  "PHCd82KHt9I": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "1Nef8LPO-jo": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "oVPWhVgEF0U": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "RyNPwIMzILw": {
    "tags": [
      "tech",
      "art"
    ]
  },
  "V3k6Eucte_A": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "Ca8LMfZXKqU": {
    "tags": [
      "tech",
      "ai",
      "gadgets"
    ]
  },
  "jufPRJ44sY0": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "y6-qcpKlzkU": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "4Gh17DmQ6n8": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "NqchrMXx2_4": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "ewmRD0MacxI": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "jmriIVcEOeE": {
    "tags": [
      "tech",
      "apple",
      "gadgets"
    ]
  },
  "Rn4si0Xorhc": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "ZZ_MBbmbgCY": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "Hlqhs-rWR8A": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "g8rfBYVbLqM": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "XTu16-fblAU": {
    "tags": [
      "tech"
    ]
  },
  "pW6cVtjIwpY": {
    "tags": [
      "tech",
      "ai",
      "gadgets"
    ]
  },
  "k0t9zOZm27E": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "gPSubG8qHNU": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "q2HPS4pBSAE": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "cy72jZ-5piA": {
    "tags": [
      "tech",
      "ai",
      "gadgets"
    ]
  },
  "gJ6N6yS63l4": {
    "tags": [
      "tech",
      "gadgets",
      "art"
    ]
  },
  "653lN9zARjc": {
    "tags": [
      "tech",
      "ai",
      "gadgets"
    ]
  },
  "lp7Xa_Md9Wg": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "HXmczdiS8m4": {
    "tags": [
      "tech",
      "ai",
      "gadgets"
    ]
  },
  "rKAHY1gfRpM": {
    "tags": [
      "tech",
      "ai",
      "apple"
    ]
  },
  "7eZb7MyqUl0": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "c9jNBQY1yi4": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "E2NWSp9vjQo": {
    "tags": [
      "tech",
      "ai"
    ]
  },
  "3KeIrBx1GQo": {
    "tags": [
      "tech",
      "ai",
      "apple"
    ]
  },
  "NUkp6hyuthM": {
    "tags": [
      "tech",
      "ai",
      "apple"
    ]
  },
  "gUx1rowghrY": {
    "tags": [
      "food-reviews"
    ]
  },
  "cotFY24lGBU": {
    "tags": [
      "tech"
    ]
  },
  "8BEg5PrvmnA": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "ZjxiNW-6aPU": {
    "tags": [
      "tech",
      "gadgets"
    ]
  },
  "roTczpcXaYk": {
    "tags": [
      "tech",
      "gadgets",
      "gaming"
    ]
  },
  "veRX00g3hXU": {
    "tags": [
      "wellness"
    ]
  },
  "vsn1cHLAzjY": {
    "tags": [
      "wellness"
    ]
  },
  "0dCwcVJBjlY": {
    "tags": [
      "wellness"
    ]
  },
  "P2USX-i8umA": {
    "tags": [
      "wellness"
    ]
  },
  "g7Ynd00perw": {
    "tags": [
      "wellness"
    ]
  },
  "8vOmzn2TFhU": {
    "tags": [
      "wellness",
      "music"
    ]
  },
  "vLhOGEnEedk": {
    "tags": [
      "wellness"
    ]
  },
  "7BKrjx5Tqos": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "wo4b51snslA": {
    "tags": [
      "wellness"
    ]
  },
  "5IQj2Yr9Ts4": {
    "tags": [
      "wellness",
      "art"
    ]
  },
  "mJM6ZX13J9Y": {
    "tags": [
      "wellness"
    ]
  },
  "fe5FDAEmN9s": {
    "tags": [
      "wellness"
    ]
  },
  "-OeeJbdy0uM": {
    "tags": [
      "wellness"
    ]
  },
  "A7Lq590io5g": {
    "tags": [
      "wellness"
    ]
  },
  "07ZaMHrBOcg": {
    "tags": [
      "wellness"
    ]
  },
  "UyUl3q5dQrs": {
    "tags": [
      "wellness"
    ]
  },
  "ffx5SovxRok": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "w-_Jt8_b_Cg": {
    "tags": [
      "wellness",
      "music"
    ]
  },
  "6hfHZssVkwg": {
    "tags": [
      "wellness"
    ]
  },
  "oDGsSZIG-1s": {
    "tags": [
      "wellness"
    ]
  },
  "XhRm175H6is": {
    "tags": [
      "wellness"
    ]
  },
  "8bTjwcUROQ4": {
    "tags": [
      "wellness"
    ]
  },
  "a6AHD8mjDC0": {
    "tags": [
      "wellness"
    ]
  },
  "OQHICAaRiQA": {
    "tags": [
      "wellness"
    ]
  },
  "HXGO0VAsjqQ": {
    "tags": [
      "wellness"
    ]
  },
  "-OIBGpdtR4c": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "9Kz81NBERDo": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "3AFiZiHOEqo": {
    "tags": [
      "wellness"
    ]
  },
  "IDbZcEqdWIg": {
    "tags": [
      "wellness"
    ]
  },
  "DiFPyfNEAkE": {
    "tags": [
      "wellness",
      "ai",
      "art"
    ]
  },
  "A454noJER-o": {
    "tags": [
      "wellness"
    ]
  },
  "eAvlih0ankY": {
    "tags": [
      "wellness",
      "ai",
      "art"
    ]
  },
  "3iEMHNgxPTo": {
    "tags": [
      "wellness"
    ]
  },
  "TY2B7yPhKwc": {
    "tags": [
      "wellness"
    ]
  },
  "O4f_IHBz-Ic": {
    "tags": [
      "wellness"
    ]
  },
  "_K4coEqF8Ng": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "AmcVDtD2NFc": {
    "tags": [
      "wellness"
    ]
  },
  "z5s60c4dzTo": {
    "tags": [
      "wellness"
    ]
  },
  "OOLEf9vaKm0": {
    "tags": [
      "wellness"
    ]
  },
  "CW_kC7lMLBA": {
    "tags": [
      "wellness"
    ]
  },
  "b-UjcG_TQ_M": {
    "tags": [
      "wellness"
    ]
  },
  "DxoSmyV9bnY": {
    "tags": [
      "wellness"
    ]
  },
  "hPL8zP-VbLw": {
    "tags": [
      "wellness"
    ]
  },
  "kBOhkoD1rms": {
    "tags": [
      "wellness"
    ]
  },
  "eNuL9KWEBQM": {
    "tags": [
      "wellness"
    ]
  },
  "ha05bNE-S1Q": {
    "tags": [
      "wellness"
    ]
  },
  "B3km15qHCeM": {
    "tags": [
      "wellness",
      "ai"
    ]
  },
  "jp7B7CEqRYk": {
    "tags": [
      "wellness"
    ]
  },
  "XZWTHu6x7js": {
    "tags": [
      "wellness"
    ]
  },
  "a-usavmn2Kw": {
    "tags": [
      "wellness"
    ]
  },
  "5HZ15Pn34J8": {
    "tags": [
      "food-reviews"
    ]
  },
  "ObtK1aIZjZ0": {
    "tags": [
      "food-reviews"
    ]
  },
  "OEvTFW3iLR4": {
    "tags": [
      "food-reviews"
    ]
  },
  "a6pkJDwpp00": {
    "tags": [
      "food-reviews"
    ]
  },
  "Hac9NHZ8BfI": {
    "tags": [
      "food-reviews"
    ]
  },
  "0QuIja6teJU": {
    "tags": [
      "food-reviews",
      "ai"
    ]
  },
  "HsLGaDj2SkE": {
    "tags": [
      "food-reviews"
    ]
  },
  "riKafVeGqq4": {
    "tags": [
      "food-reviews"
    ]
  },
  "E06vZMVF-04": {
    "tags": [
      "food-reviews"
    ]
  },
  "fLZdXiuMCoU": {
    "tags": [
      "food-reviews"
    ]
  },
  "Rt9sYDj3RW4": {
    "tags": [
      "food-reviews"
    ]
  },
  "hgHzuwb3les": {
    "tags": [
      "food-reviews"
    ]
  },
  "-ar_x2wl-RI": {
    "tags": [
      "food-reviews"
    ]
  },
  "whDUtflCK9g": {
    "tags": [
      "food-reviews"
    ]
  },
  "RvElE2PZC38": {
    "tags": [
      "food-reviews"
    ]
  },
  "YTcACmX7Zrk": {
    "tags": [
      "food-reviews"
    ]
  },
  "e3nGhxYvIC8": {
    "tags": [
      "food-reviews"
    ]
  },
  "V37TZtVzTfs": {
    "tags": [
      "food-reviews"
    ]
  },
  "Ki3v6IeL-LY": {
    "tags": [
      "food-reviews"
    ]
  },
  "EQdJRpGp9RA": {
    "tags": [
      "food-reviews"
    ]
  },
  "yGchce4t_KA": {
    "tags": [
      "food-reviews"
    ]
  },
  "hNWlzIZexNc": {
    "tags": [
      "food-reviews"
    ]
  },
  "K_YRRoVwH38": {
    "tags": [
      "food-reviews"
    ]
  },
  "f-YVSBHPTh4": {
    "tags": [
      "food-reviews"
    ]
  },
  "f4CEcPHP2LA": {
    "tags": [
      "food-reviews"
    ]
  },
  "jIUr9BGzfhw": {
    "tags": [
      "food-reviews"
    ]
  },
  "eO009Rne5KU": {
    "tags": [
      "food-reviews"
    ]
  },
  "4ZlbsjTfNc0": {
    "tags": [
      "food-reviews"
    ]
  },
  "NEhrP1YoWhI": {
    "tags": [
      "food-reviews"
    ]
  },
  "MtEEcrzWzy8": {
    "tags": [
      "food-reviews"
    ]
  },
  "Elj2gaht5SI": {
    "tags": [
      "food-reviews"
    ]
  },
  "XPzCEKkFp2w": {
    "tags": [
      "food-reviews"
    ]
  },
  "7sFOBqXLVBo": {
    "tags": [
      "food-reviews"
    ]
  },
  "8-ue9VwiHCY": {
    "tags": [
      "food-reviews",
      "ai"
    ]
  },
  "F-H-CBstv20": {
    "tags": [
      "food-reviews"
    ]
  },
  "B8jUsYnIuXs": {
    "tags": [
      "food-reviews"
    ]
  },
  "jHkteJ3_elw": {
    "tags": [
      "food-reviews"
    ]
  },
  "alg9ydZDre0": {
    "tags": [
      "food-reviews",
      "food"
    ]
  },
  "ZKFKjQmBgvI": {
    "tags": [
      "food-reviews"
    ]
  },
  "41xEYyILlg8": {
    "tags": [
      "food-reviews"
    ]
  },
  "g0R3wVL7ZS8": {
    "tags": [
      "food-reviews"
    ]
  },
  "9p7gpLUmCJc": {
    "tags": [
      "food-reviews"
    ]
  },
  "jktUV8nVR_w": {
    "tags": [
      "food-reviews"
    ]
  },
  "5zf17-dDNl0": {
    "tags": [
      "food-reviews"
    ]
  },
  "_subUPojRGY": {
    "tags": [
      "food-reviews"
    ]
  },
  "EATsj7__fVw": {
    "tags": [
      "food-reviews"
    ]
  },
  "j8JOEM8nUoU": {
    "tags": [
      "food-reviews",
      "ai"
    ]
  },
  "Wa76zJrlT9M": {
    "tags": [
      "food-reviews"
    ]
  },
  "xod6Q5xJQbA": {
    "tags": [
      "food-reviews"
    ]
  },
  "1RSsFvrzHAM": {
    "tags": [
      "outdoors",
      "food"
    ]
  },
  "NIinPQzmVEw": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "RLmUxXO8pKs": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "SwvDwEtPJXc": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "p1m2s1En6DQ": {
    "tags": [
      "outdoors",
      "food"
    ]
  },
  "wX4XtKq9YSI": {
    "tags": [
      "outdoors"
    ]
  },
  "EKO6hOUnbgE": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "YLJ7t1eXUwU": {
    "tags": [
      "outdoors"
    ]
  },
  "aeAomwSwWNk": {
    "tags": [
      "outdoors"
    ]
  },
  "A5V1bodiE24": {
    "tags": [
      "outdoors"
    ]
  },
  "9eUUVTIejOM": {
    "tags": [
      "outdoors",
      "food"
    ]
  },
  "C2gfPUymsVE": {
    "tags": [
      "outdoors"
    ]
  },
  "ODkSwmVULnc": {
    "tags": [
      "outdoors"
    ]
  },
  "1B0sSHIxsio": {
    "tags": [
      "outdoors"
    ]
  },
  "TAYSvd2dXUA": {
    "tags": [
      "outdoors",
      "food"
    ]
  },
  "-8tLy0F2mAI": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "nUBCDS_htqQ": {
    "tags": [
      "outdoors"
    ]
  },
  "OXJjVZ4v5qM": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "mp0e447HO5o": {
    "tags": [
      "outdoors"
    ]
  },
  "oP7OqHMwMHE": {
    "tags": [
      "outdoors"
    ]
  },
  "xAr1PZUmd58": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "7v6UuYn94Jc": {
    "tags": [
      "outdoors",
      "music"
    ]
  },
  "neM7q7JIZXQ": {
    "tags": [
      "outdoors"
    ]
  },
  "a9SippcycZw": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "p_t32zAUZv0": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "nCr2JxYzjHs": {
    "tags": [
      "outdoors"
    ]
  },
  "Y2WSY7WCCVU": {
    "tags": [
      "outdoors"
    ]
  },
  "FaQ2VX39yOU": {
    "tags": [
      "outdoors"
    ]
  },
  "3DOCc19EDk0": {
    "tags": [
      "outdoors"
    ]
  },
  "N1934B5vaGI": {
    "tags": [
      "outdoors"
    ]
  },
  "3GdfcFMnikY": {
    "tags": [
      "outdoors"
    ]
  },
  "rajvlHa_8Ac": {
    "tags": [
      "outdoors"
    ]
  },
  "Wh70S2ktEic": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "CZM7meU9c9s": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "JhRY7_0g8zc": {
    "tags": [
      "outdoors"
    ]
  },
  "jgXkDlORWG4": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "f-YtAyt2H44": {
    "tags": [
      "outdoors"
    ]
  },
  "dyaiHH4Do6M": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "6Uqdo9sQrDU": {
    "tags": [
      "outdoors"
    ]
  },
  "6jGAhD1-g2I": {
    "tags": [
      "outdoors"
    ]
  },
  "UN7loEnnCBw": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "6Z7Gr3wb3wo": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "LVrJopDKdO4": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "_IiR2Sqw1p8": {
    "tags": [
      "outdoors"
    ]
  },
  "IMIEvNbqEZ8": {
    "tags": [
      "outdoors"
    ]
  },
  "rDTXhpM189s": {
    "tags": [
      "outdoors",
      "art"
    ]
  },
  "ws_swlSbjuo": {
    "tags": [
      "outdoors"
    ]
  },
  "4dyk6Yzq1Zo": {
    "tags": [
      "cars",
      "art"
    ]
  },
  "gXDc1S7zGQY": {
    "tags": [
      "outdoors",
      "ai"
    ]
  },
  "Unz5qZ0lsoM": {
    "tags": [
      "outdoors"
    ]
  },
  "ZNxHPL0m4N4": {
    "tags": [
      "outdoors"
    ]
  },
  "Bs6n2McqkDk": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "tvH5SQv4tsY": {
    "tags": [
      "cars"
    ]
  },
  "EQiuc9sgRfk": {
    "tags": [
      "cars"
    ]
  },
  "zjJbS5DLgRY": {
    "tags": [
      "cars",
      "finance",
      "art"
    ]
  },
  "poBJQJzELE4": {
    "tags": [
      "cars"
    ]
  },
  "3aiAxE53yhA": {
    "tags": [
      "cars"
    ]
  },
  "8kOj-Xqy8MM": {
    "tags": [
      "cars"
    ]
  },
  "G4ZksvItUno": {
    "tags": [
      "cars"
    ]
  },
  "cx6Z3lbzJbk": {
    "tags": [
      "cars"
    ]
  },
  "4Cy-KtZrw3U": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "8ZVp_2S5ycA": {
    "tags": [
      "cars"
    ]
  },
  "kX6fMTQ2vXg": {
    "tags": [
      "cars"
    ]
  },
  "aOw4xspSgoU": {
    "tags": [
      "cars"
    ]
  },
  "tpd-zNHnxOI": {
    "tags": [
      "cars"
    ]
  },
  "vAe-WQf81og": {
    "tags": [
      "cars",
      "art"
    ]
  },
  "5Nq7LoP1ySI": {
    "tags": [
      "cars"
    ]
  },
  "ZBaTkSbX9Dw": {
    "tags": [
      "cars"
    ]
  },
  "rTsaEhZzeyo": {
    "tags": [
      "cars"
    ]
  },
  "4E3VSdt7LPM": {
    "tags": [
      "cars"
    ]
  },
  "0fDTAoy8VRs": {
    "tags": [
      "cars"
    ]
  },
  "dHBhxAjrmck": {
    "tags": [
      "cars",
      "ai",
      "art"
    ]
  },
  "wdgEjZHYWmc": {
    "tags": [
      "cars"
    ]
  },
  "odePaN4f4R0": {
    "tags": [
      "cars",
      "art"
    ]
  },
  "Uoph_ctbNfQ": {
    "tags": [
      "cars"
    ]
  },
  "-KSWKc0qhtM": {
    "tags": [
      "cars"
    ]
  },
  "5bxPvrUNlvE": {
    "tags": [
      "cars"
    ]
  },
  "Xzul1TWCMa4": {
    "tags": [
      "cars"
    ]
  },
  "-lYNv6BHj2M": {
    "tags": [
      "cars"
    ]
  },
  "btrDZ5iJ0pI": {
    "tags": [
      "cars"
    ]
  },
  "7wRchKFAA7Q": {
    "tags": [
      "cars"
    ]
  },
  "WBK0kTmYAqQ": {
    "tags": [
      "cars"
    ]
  },
  "pci_MregRF0": {
    "tags": [
      "cars"
    ]
  },
  "n23JJRQqX3U": {
    "tags": [
      "cars",
      "art"
    ]
  },
  "KbnJpszA53U": {
    "tags": [
      "cars"
    ]
  },
  "38eBOMlUoaw": {
    "tags": [
      "cars"
    ]
  },
  "Sjs4znjjCGM": {
    "tags": [
      "cars"
    ]
  },
  "-Ezkcsg3EAA": {
    "tags": [
      "cars"
    ]
  },
  "mhJb7HyPLBk": {
    "tags": [
      "cars"
    ]
  },
  "wh7e1-Gikf8": {
    "tags": [
      "cars"
    ]
  },
  "9YFZ-pAsoKQ": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "R2pagIizWNI": {
    "tags": [
      "cars"
    ]
  },
  "FBnBVd52PHs": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "xgw2J0MOG7M": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "PtrlTm6adNk": {
    "tags": [
      "cars"
    ]
  },
  "TwiqTNMbu20": {
    "tags": [
      "cars"
    ]
  },
  "ifSg1Ti2Us0": {
    "tags": [
      "cars"
    ]
  },
  "xh4LwGb7C60": {
    "tags": [
      "cars",
      "art"
    ]
  },
  "qzBKWlF4YTc": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "BA2vByjKWXE": {
    "tags": [
      "cars",
      "ai"
    ]
  },
  "lv9CrpcbQtc": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "6RxrK0fJW1k": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "9aBz4G5OfGg": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "m6x95SumTU0": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "68LCJZiASuA": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "v2g5qbvb7F4": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "nC2NvA-A_wI": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "zuH2KsJukjM": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "-cYzPZEh0dI": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "4sJYMJUGl_o": {
    "tags": [
      "art"
    ]
  },
  "H06H6A5-gro": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "0NT443zwMYE": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "DXqxM6MQKK8": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "SH5iNH3WEtw": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "2F-p0zo3qZs": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "py6uzr7ZGLg": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "I4RzDc3Z5e4": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "TwFOyrB3-ts": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "PUnocCdRccI": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "WQiJgRpbgJs": {
    "tags": [
      "art"
    ]
  },
  "Mg76l2zXoIQ": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "0XbmapaLsBE": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "6oe1TAGBGLw": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "wj52Igj8Bbg": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "4dKeFrDslTU": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "al-GR0WBsWg": {
    "tags": [
      "art"
    ]
  },
  "abLEJ3DN6J8": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "DEJK93k9ZD4": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "5Eta2uzQPA8": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "lelvqx4nWGE": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "fcwB-7ZCaAc": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "mRiJejtGDU0": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "tllrgrwjEIY": {
    "tags": [
      "art"
    ]
  },
  "7BbMqwM0ZDc": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "xGMDx3CUnvg": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "Av9mEPrwgWg": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "jb9si7T_Kgo": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "1w6i-fR6N8s": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "_Lkwho1mnOc": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "NtJjaLS-OR8": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "g62JjvsdY5k": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "UL39S3Hirlo": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "KQLKuhlsWII": {
    "tags": [
      "art"
    ]
  },
  "3w3bo_nk_5U": {
    "tags": [
      "art"
    ]
  },
  "bz2w9IHyyxQ": {
    "tags": [
      "art",
      "ai",
      "photography"
    ]
  },
  "yy2GbP76eAs": {
    "tags": [
      "art"
    ]
  },
  "eisS79Cdhuk": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "9mRx3hIYlvQ": {
    "tags": [
      "art"
    ]
  },
  "UcVUz20prAs": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "hu9Bjsz2hKU": {
    "tags": [
      "art",
      "ai"
    ]
  },
  "ztPKM0nryY8": {
    "tags": [
      "education",
      "ai",
      "science"
    ]
  },
  "5yn0NXB_5Ro": {
    "tags": [
      "education"
    ]
  },
  "0MwJHzs8uuY": {
    "tags": [
      "education"
    ]
  },
  "23GzGSc5kLE": {
    "tags": [
      "education"
    ]
  },
  "8q_yrYeE2pM": {
    "tags": [
      "education",
      "art"
    ]
  },
  "n2bXfbTRYbY": {
    "tags": [
      "education"
    ]
  },
  "MCYffN0eGLo": {
    "tags": [
      "education",
      "gadgets",
      "art"
    ]
  },
  "6E10ebsKg0M": {
    "tags": [
      "education"
    ]
  },
  "0ls37smQRXc": {
    "tags": [
      "education"
    ]
  },
  "tk3fCn3bG2E": {
    "tags": [
      "education",
      "music"
    ]
  },
  "QxTcngjaQkE": {
    "tags": [
      "education",
      "ai"
    ]
  },
  "cnXwXXvZczA": {
    "tags": [
      "education"
    ]
  },
  "mTZFEvgGq14": {
    "tags": [
      "education"
    ]
  },
  "DPWP0wRP07U": {
    "tags": [
      "education",
      "art",
      "music"
    ]
  },
  "QF29aPV3Sqk": {
    "tags": [
      "education"
    ]
  },
  "IimvI9M5K3A": {
    "tags": [
      "education"
    ]
  },
  "bv7SpN8pq2I": {
    "tags": [
      "education"
    ]
  },
  "0VTBNSaHTFc": {
    "tags": [
      "education",
      "ai"
    ]
  },
  "116ZFkoQYBs": {
    "tags": [
      "education",
      "ai",
      "science"
    ]
  },
  "lA6ONFMTdwE": {
    "tags": [
      "education"
    ]
  },
  "dEYSBvRA6AY": {
    "tags": [
      "education",
      "art"
    ]
  },
  "xH5HEB6NxWs": {
    "tags": [
      "education"
    ]
  },
  "LO8K6ul13JQ": {
    "tags": [
      "education",
      "art"
    ]
  },
  "IpnHd-t8j4s": {
    "tags": [
      "education"
    ]
  },
  "L_MvKT-WwEc": {
    "tags": [
      "education",
      "ai"
    ]
  },
  "3bUnm42Yehk": {
    "tags": [
      "education"
    ]
  },
  "dI_FsUsJAVY": {
    "tags": [
      "education"
    ]
  },
  "SwLSNIbGSnE": {
    "tags": [
      "education",
      "music"
    ]
  },
  "gVEdYP1j-6o": {
    "tags": [
      "education"
    ]
  },
  "FaIfTN8JZ18": {
    "tags": [
      "education"
    ]
  },
  "x8lmj5Wix4U": {
    "tags": [
      "education"
    ]
  },
  "_Zm96V6hRiM": {
    "tags": [
      "education",
      "art"
    ]
  },
  "fmzoGr8m1bM": {
    "tags": [
      "education"
    ]
  },
  "lifq0qUMm7E": {
    "tags": [
      "education",
      "science"
    ]
  },
  "vjZ2qWJQpo4": {
    "tags": [
      "education"
    ]
  },
  "zamt_1PAwqE": {
    "tags": [
      "education"
    ]
  },
  "Vsb-olADGZ4": {
    "tags": [
      "education"
    ]
  },
  "eE5TJKZ0-jg": {
    "tags": [
      "education"
    ]
  },
  "G1JPyIbKJG0": {
    "tags": [
      "education"
    ]
  },
  "qYNqkBPcI7c": {
    "tags": [
      "education"
    ]
  },
  "rWk-iUta_lI": {
    "tags": [
      "education",
      "art"
    ]
  },
  "IyjY4IloK3k": {
    "tags": [
      "education"
    ]
  },
  "cRaSPHY9pPk": {
    "tags": [
      "education"
    ]
  },
  "GnYwJogIyUM": {
    "tags": [
      "education"
    ]
  },
  "kxOFEpLKNpk": {
    "tags": [
      "education"
    ]
  },
  "erTtDnf0rk4": {
    "tags": [
      "education"
    ]
  },
  "yOpZ5dz8yng": {
    "tags": [
      "education",
      "art"
    ]
  },
  "l6tgf1oIomc": {
    "tags": [
      "education"
    ]
  },
  "EcBC6JH57Fw": {
    "tags": [
      "education"
    ]
  },
  "SbgBeIs1VQA": {
    "tags": [
      "education",
      "ai"
    ]
  },
  "G-KYX7d1sJc": {
    "tags": [
      "parenting",
      "art"
    ]
  },
  "_BgwT6QKlb0": {
    "tags": [
      "parenting"
    ]
  },
  "-G49u2y-0U4": {
    "tags": [
      "parenting"
    ]
  },
  "ICOt9pdL7Vg": {
    "tags": [
      "parenting"
    ]
  },
  "6M3rm0uM6dc": {
    "tags": [
      "parenting",
      "art"
    ]
  },
  "0hHxwMrfyLI": {
    "tags": [
      "parenting"
    ]
  },
  "w8sB13HRwXc": {
    "tags": [
      "parenting"
    ]
  },
  "HW7WYzdfqFs": {
    "tags": [
      "parenting"
    ]
  },
  "FfSpDDBsCFs": {
    "tags": [
      "parenting",
      "art"
    ]
  },
  "Npc29n7yMmM": {
    "tags": [
      "parenting"
    ]
  },
  "ckJL1TMtDlM": {
    "tags": [
      "parenting"
    ]
  },
  "CTnfsi8XLFc": {
    "tags": [
      "parenting"
    ]
  },
  "00GhgwLDoxQ": {
    "tags": [
      "parenting"
    ]
  },
  "0SQ61dZu61Y": {
    "tags": [
      "parenting"
    ]
  },
  "MyGnCJZKMws": {
    "tags": [
      "parenting"
    ]
  },
  "DX_UDZdKkp0": {
    "tags": [
      "parenting"
    ]
  },
  "Eu8k4yItBjQ": {
    "tags": [
      "parenting"
    ]
  },
  "EPGamr18AA4": {
    "tags": [
      "parenting"
    ]
  },
  "MyxvpYKNfQc": {
    "tags": [
      "parenting"
    ]
  },
  "-Nf6tZst7fw": {
    "tags": [
      "parenting"
    ]
  },
  "NsU98S_LBLM": {
    "tags": [
      "parenting"
    ]
  },
  "MMeR-Ixpmgs": {
    "tags": [
      "parenting"
    ]
  },
  "NvFtEDN6oLg": {
    "tags": [
      "parenting"
    ]
  },
  "hCChswZdpAU": {
    "tags": [
      "parenting"
    ]
  },
  "cs6S4Xdxmnk": {
    "tags": [
      "parenting",
      "art"
    ]
  },
  "q0865X62wQQ": {
    "tags": [
      "parenting"
    ]
  },
  "dBhTo8Q_-3c": {
    "tags": [
      "parenting"
    ]
  },
  "3UOYwNl_8t4": {
    "tags": [
      "parenting"
    ]
  },
  "zv2mxjE2yEE": {
    "tags": [
      "parenting"
    ]
  },
  "8MykJPV71ag": {
    "tags": [
      "parenting"
    ]
  },
  "DxtJvcy2_80": {
    "tags": [
      "parenting"
    ]
  },
  "ooNepQlgj28": {
    "tags": [
      "parenting"
    ]
  },
  "PqVg_u7VUwA": {
    "tags": [
      "parenting",
      "ai",
      "fitness"
    ]
  },
  "--NM-4ol9zE": {
    "tags": [
      "parenting"
    ]
  },
  "LYc45TW0eEg": {
    "tags": [
      "parenting"
    ]
  },
  "GCcspzibKnU": {
    "tags": [
      "parenting"
    ]
  },
  "oJrQxYGKQuY": {
    "tags": [
      "parenting"
    ]
  },
  "9ycVKcl7qoA": {
    "tags": [
      "parenting"
    ]
  },
  "4-CEHukMweE": {
    "tags": [
      "parenting"
    ]
  },
  "ki31KIvix1Q": {
    "tags": [
      "parenting"
    ]
  },
  "uevN06TFbbM": {
    "tags": [
      "parenting"
    ]
  },
  "39doWqmp_D0": {
    "tags": [
      "parenting"
    ]
  },
  "kbSmis0xl9k": {
    "tags": [
      "parenting"
    ]
  },
  "sbDuAl98TVg": {
    "tags": [
      "parenting",
      "art"
    ]
  },
  "7ylSAb1bhG4": {
    "tags": [
      "parenting"
    ]
  },
  "29ESP82CCQ8": {
    "tags": [
      "parenting",
      "ai"
    ]
  },
  "3JeCM_NnU8g": {
    "tags": [
      "parenting"
    ]
  },
  "mUBvDbMKR1c": {
    "tags": [
      "parenting"
    ]
  },
  "6Rjiblh5Up0": {
    "tags": [
      "parenting"
    ]
  },
  "yLOFR_4rQiE": {
    "tags": [
      "parenting"
    ]
  },
  "1cewLNYF7Ew": {
    "tags": [
      "real-estate"
    ]
  },
  "5tTtzRH1QAQ": {
    "tags": [
      "real-estate"
    ]
  },
  "D0fSsvBen0Y": {
    "tags": [
      "real-estate"
    ]
  },
  "-xVW8qjZLPs": {
    "tags": [
      "real-estate"
    ]
  },
  "NFe7x0DW6nM": {
    "tags": [
      "real-estate"
    ]
  },
  "ye7eRew9pgg": {
    "tags": [
      "real-estate"
    ]
  },
  "VKAKbueezMk": {
    "tags": [
      "real-estate",
      "music"
    ]
  },
  "0dZo7m08E-U": {
    "tags": [
      "real-estate"
    ]
  },
  "FawkW1DPUzs": {
    "tags": [
      "real-estate"
    ]
  },
  "uWab5MwaFx0": {
    "tags": [
      "real-estate"
    ]
  },
  "y9j-BL5ocW8": {
    "tags": [
      "real-estate"
    ]
  },
  "bygZUkbHNFQ": {
    "tags": [
      "real-estate"
    ]
  },
  "GjYS3x3xLtk": {
    "tags": [
      "real-estate"
    ]
  },
  "3pkZO5MGQS8": {
    "tags": [
      "real-estate",
      "ai"
    ]
  },
  "NsBqpEuizPo": {
    "tags": [
      "real-estate",
      "ai"
    ]
  },
  "0zPdqJFBvhU": {
    "tags": [
      "real-estate"
    ]
  },
  "AQYz-fb3BCc": {
    "tags": [
      "real-estate"
    ]
  },
  "4jnzf1yj48M": {
    "tags": [
      "real-estate",
      "ai",
      "music"
    ]
  },
  "mtpCX5FVJEc": {
    "tags": [
      "real-estate"
    ]
  },
  "Ms0eZBrLMuk": {
    "tags": [
      "real-estate"
    ]
  },
  "hu_RrgSMGXM": {
    "tags": [
      "real-estate"
    ]
  },
  "3H6Evu2hPpE": {
    "tags": [
      "real-estate"
    ]
  },
  "WwoFskyU020": {
    "tags": [
      "real-estate"
    ]
  },
  "zPLzHeKRe-0": {
    "tags": [
      "real-estate",
      "apple",
      "art"
    ]
  },
  "daGwEG0a7-g": {
    "tags": [
      "real-estate"
    ]
  },
  "ziKIKaxLHEc": {
    "tags": [
      "real-estate",
      "apple"
    ]
  },
  "kg3kJ-bo8rU": {
    "tags": [
      "real-estate"
    ]
  },
  "a3L9yGcVO2g": {
    "tags": [
      "real-estate"
    ]
  },
  "0fGgzxc7Qxo": {
    "tags": [
      "real-estate",
      "ai"
    ]
  },
  "InJT_fN4zkU": {
    "tags": [
      "real-estate"
    ]
  },
  "OcvB8LcNSgI": {
    "tags": [
      "real-estate"
    ]
  },
  "xPSrgeEeNMw": {
    "tags": [
      "real-estate"
    ]
  },
  "Yn_BUjUKWDU": {
    "tags": [
      "real-estate"
    ]
  },
  "2v_7UH_nLv4": {
    "tags": [
      "real-estate"
    ]
  },
  "TCcfUKPZ_Ik": {
    "tags": [
      "real-estate"
    ]
  },
  "poygyZy1uEQ": {
    "tags": [
      "real-estate"
    ]
  },
  "8EN3E1V7Uiw": {
    "tags": [
      "real-estate",
      "ai"
    ]
  },
  "foeDvpNrVtI": {
    "tags": [
      "real-estate"
    ]
  },
  "NGRfk1NL5f0": {
    "tags": [
      "real-estate"
    ]
  },
  "42heSC7KPOI": {
    "tags": [
      "real-estate"
    ]
  },
  "Q1Nrtia04gE": {
    "tags": [
      "real-estate",
      "art"
    ]
  },
  "DVSFt1US0TQ": {
    "tags": [
      "real-estate"
    ]
  },
  "BFM1wX8orCs": {
    "tags": [
      "real-estate"
    ]
  },
  "MQXxCE93kN4": {
    "tags": [
      "real-estate"
    ]
  },
  "hdtF9da8dO8": {
    "tags": [
      "real-estate"
    ]
  },
  "Ra2R0MB0YUs": {
    "tags": [
      "real-estate"
    ]
  },
  "6cXawULEjlE": {
    "tags": [
      "real-estate",
      "ai"
    ]
  },
  "hp7uZ3BBNOc": {
    "tags": [
      "real-estate"
    ]
  },
  "gO-3KSPsu0Y": {
    "tags": [
      "real-estate",
      "art"
    ]
  },
  "KPsNDC1BGOc": {
    "tags": [
      "real-estate"
    ]
  },
  "YB891ggzItI": {
    "tags": [
      "photography"
    ]
  },
  "souKz302luU": {
    "tags": [
      "photography"
    ]
  },
  "fhFFDoGyZhY": {
    "tags": [
      "photography"
    ]
  },
  "UV5cvvYmJJI": {
    "tags": [
      "photography"
    ]
  },
  "Y4ufUshGKlk": {
    "tags": [
      "photography"
    ]
  },
  "OrG5iQ7-Vkc": {
    "tags": [
      "photography"
    ]
  },
  "0cCC9gQUX9Y": {
    "tags": [
      "photography"
    ]
  },
  "EYekftCtrDc": {
    "tags": [
      "photography"
    ]
  },
  "Ahc7FzH2Hbw": {
    "tags": [
      "photography"
    ]
  },
  "HJnZM3UUCKk": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "LKMwPPnEMSs": {
    "tags": [
      "photography"
    ]
  },
  "2GZ-FdjTNK8": {
    "tags": [
      "photography"
    ]
  },
  "bqrDMyEsVTc": {
    "tags": [
      "photography",
      "ai"
    ]
  },
  "2qRaH-WyLx0": {
    "tags": [
      "photography",
      "art",
      "music"
    ]
  },
  "MG2Iw3Ttd7w": {
    "tags": [
      "photography",
      "art"
    ]
  },
  "y_DoKWljZ50": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "SpAWFMkjmoo": {
    "tags": [
      "photography"
    ]
  },
  "Y1IfZYirBKo": {
    "tags": [
      "photography"
    ]
  },
  "sHj5zK1MaQY": {
    "tags": [
      "photography"
    ]
  },
  "fXrChhug2XU": {
    "tags": [
      "photography"
    ]
  },
  "xZ_vOmH0T5w": {
    "tags": [
      "photography",
      "ai"
    ]
  },
  "QpQQ7Dbxv6w": {
    "tags": [
      "photography",
      "ai"
    ]
  },
  "VjR9rPxcqfU": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "5B6ZU3sIDTs": {
    "tags": [
      "photography",
      "art"
    ]
  },
  "rrrYVSIkPwU": {
    "tags": [
      "photography"
    ]
  },
  "vAvea8VRwhk": {
    "tags": [
      "photography"
    ]
  },
  "SR__amDl1c8": {
    "tags": [
      "photography"
    ]
  },
  "ZpSO-kYo8u8": {
    "tags": [
      "photography",
      "art"
    ]
  },
  "0RHLjr5kL9Y": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "osBOcnywNPQ": {
    "tags": [
      "photography"
    ]
  },
  "Ppp27j80-_4": {
    "tags": [
      "photography"
    ]
  },
  "iFuIGIA85mA": {
    "tags": [
      "photography"
    ]
  },
  "NYm2gXtYk2c": {
    "tags": [
      "photography",
      "ai"
    ]
  },
  "6gYZuDZrx14": {
    "tags": [
      "photography",
      "art"
    ]
  },
  "0zzKeOwBlPc": {
    "tags": [
      "photography"
    ]
  },
  "SFyBEOkni0Y": {
    "tags": [
      "photography"
    ]
  },
  "1qLfqVw1K_w": {
    "tags": [
      "photography"
    ]
  },
  "7wTdRMUD1Tg": {
    "tags": [
      "photography"
    ]
  },
  "IJMce7q51Ns": {
    "tags": [
      "photography"
    ]
  },
  "68IblY_pRo4": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "C1tixHYPtuI": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "bGIQSmuCRUE": {
    "tags": [
      "photography"
    ]
  },
  "gZ66UZpIfUY": {
    "tags": [
      "photography",
      "apple"
    ]
  },
  "JiSZ_ePXs7A": {
    "tags": [
      "photography"
    ]
  },
  "_gTxKwhw_ME": {
    "tags": [
      "photography"
    ]
  },
  "YmxdUOyY6dQ": {
    "tags": [
      "photography",
      "fitness"
    ]
  },
  "_RWohowsEKo": {
    "tags": [
      "photography"
    ]
  },
  "8rdud6qJqnU": {
    "tags": [
      "photography",
      "art"
    ]
  },
  "WMrQLDdwGgU": {
    "tags": [
      "photography"
    ]
  },
  "BsblgcBB17A": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "XnjiprcNurg": {
    "tags": [
      "motivation"
    ]
  },
  "GHGcF30-j_E": {
    "tags": [
      "motivation",
      "art",
      "music"
    ]
  },
  "rqhip-F4i9c": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "uMKNhS8BDuE": {
    "tags": [
      "motivation"
    ]
  },
  "S0pYBB8uB20": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "jGaerJSRxc8": {
    "tags": [
      "motivation"
    ]
  },
  "-LNZzgtRHEE": {
    "tags": [
      "motivation",
      "ai",
      "art"
    ]
  },
  "uR-TIrylmR4": {
    "tags": [
      "motivation"
    ]
  },
  "ERClHCOF14c": {
    "tags": [
      "motivation"
    ]
  },
  "XcSdPK5Xwbk": {
    "tags": [
      "motivation",
      "art"
    ]
  },
  "2liO8zHVGBs": {
    "tags": [
      "motivation"
    ]
  },
  "MqD9pMeVZvk": {
    "tags": [
      "motivation"
    ]
  },
  "LtElHdyVfY0": {
    "tags": [
      "motivation"
    ]
  },
  "20aoQpxm4gc": {
    "tags": [
      "motivation"
    ]
  },
  "rxV-41MMmsM": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "s0xy9Bsmgv8": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "NYCCe3jWHeo": {
    "tags": [
      "motivation"
    ]
  },
  "Oll8rheB1TM": {
    "tags": [
      "motivation"
    ]
  },
  "1XZ3xIXPK5o": {
    "tags": [
      "relationships"
    ]
  },
  "M76BnPaRUEk": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "7fLqPBK_Z9o": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "WzDuFaVkLac": {
    "tags": [
      "motivation"
    ]
  },
  "E7J5cEvu6kI": {
    "tags": [
      "motivation"
    ]
  },
  "idRnwDMARmU": {
    "tags": [
      "motivation"
    ]
  },
  "5f7E4DQG6kk": {
    "tags": [
      "motivation"
    ]
  },
  "fHyQSQd6fQ4": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "ANEokonLIPg": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "_mo7r-hI6Xo": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "AO3vWcMQu_0": {
    "tags": [
      "motivation"
    ]
  },
  "EsChabDcB1c": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "gxEHvKiwcAM": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "rXaF79N0jQw": {
    "tags": [
      "motivation"
    ]
  },
  "i4D_3IF35C0": {
    "tags": [
      "motivation"
    ]
  },
  "DfLu1z6e79Q": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "vmUecskGcXs": {
    "tags": [
      "motivation"
    ]
  },
  "48BnYG54694": {
    "tags": [
      "motivation"
    ]
  },
  "ZwcaFhdjRY4": {
    "tags": [
      "motivation"
    ]
  },
  "Mk1hdqQG07k": {
    "tags": [
      "motivation"
    ]
  },
  "t6SQ5ld6NvE": {
    "tags": [
      "motivation"
    ]
  },
  "F9YG4QgFZnc": {
    "tags": [
      "motivation",
      "art"
    ]
  },
  "0Wu7SolaRpk": {
    "tags": [
      "motivation"
    ]
  },
  "CPUb9kK14kk": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "k32vVwkxSl8": {
    "tags": [
      "motivation"
    ]
  },
  "bZacNmY5kig": {
    "tags": [
      "motivation"
    ]
  },
  "wnHW6o8WMas": {
    "tags": [
      "motivation"
    ]
  },
  "7FkZYYgk-Jg": {
    "tags": [
      "motivation"
    ]
  },
  "2CxVDbrzxaw": {
    "tags": [
      "motivation",
      "ai"
    ]
  },
  "k7ChMqZUa5s": {
    "tags": [
      "motivation"
    ]
  },
  "lvniZRRaD7w": {
    "tags": [
      "motivation",
      "ai",
      "art"
    ]
  },
  "h3Nqbx7mbAo": {
    "tags": [
      "motivation"
    ]
  },
  "fZS-c7OEjxU": {
    "tags": [
      "relationships",
      "ai"
    ]
  },
  "7XnT4l0msj4": {
    "tags": [
      "relationships"
    ]
  },
  "hcc2NL0CL98": {
    "tags": [
      "relationships"
    ]
  },
  "eYvSW9GZIMg": {
    "tags": [
      "relationships"
    ]
  },
  "gaRheYMOykM": {
    "tags": [
      "relationships"
    ]
  },
  "Lav1Vd4nV-c": {
    "tags": [
      "relationships"
    ]
  },
  "FzFXbLCWrJI": {
    "tags": [
      "relationships"
    ]
  },
  "ciSaIpoo0XI": {
    "tags": [
      "relationships"
    ]
  },
  "qSdUNfAuc3w": {
    "tags": [
      "relationships",
      "art"
    ]
  },
  "h_KK6ubngfw": {
    "tags": [
      "relationships",
      "ai"
    ]
  },
  "MtbHDwh-m18": {
    "tags": [
      "relationships"
    ]
  },
  "jfPb2AEgH1c": {
    "tags": [
      "relationships",
      "ai"
    ]
  },
  "hJJtjk6RYCs": {
    "tags": [
      "relationships"
    ]
  },
  "7WsjN3veDKk": {
    "tags": [
      "relationships"
    ]
  },
  "amMvXqzXB38": {
    "tags": [
      "relationships"
    ]
  },
  "05oHspx8VII": {
    "tags": [
      "relationships"
    ]
  },
  "8V3TMEyfoC8": {
    "tags": [
      "relationships"
    ]
  },
  "zuM5XMmj9vE": {
    "tags": [
      "relationships"
    ]
  },
  "DgpJjB5Bpxo": {
    "tags": [
      "relationships"
    ]
  },
  "651KO4t59gk": {
    "tags": [
      "relationships"
    ]
  },
  "yo0mGCckzLA": {
    "tags": [
      "relationships"
    ]
  },
  "AO9Vt4uB2I8": {
    "tags": [
      "relationships"
    ]
  },
  "cevF_wdzjDY": {
    "tags": [
      "relationships"
    ]
  },
  "1r0w6tJj6vg": {
    "tags": [
      "relationships"
    ]
  },
  "bzm84nEEn4E": {
    "tags": [
      "relationships"
    ]
  },
  "7UeTQWbYiLY": {
    "tags": [
      "relationships"
    ]
  },
  "UGrakG9DXyQ": {
    "tags": [
      "relationships"
    ]
  },
  "p7Jzd4mPO2o": {
    "tags": [
      "relationships"
    ]
  },
  "VpQxWUZ3x48": {
    "tags": [
      "relationships"
    ]
  },
  "SnW6QNm-Ny8": {
    "tags": [
      "relationships",
      "ai"
    ]
  },
  "W06CBStwPC8": {
    "tags": [
      "relationships"
    ]
  },
  "E7CiEf3H8zM": {
    "tags": [
      "relationships"
    ]
  },
  "BAZOIebmPZA": {
    "tags": [
      "relationships"
    ]
  },
  "d__S-ETQgYQ": {
    "tags": [
      "relationships"
    ]
  },
  "Lo212CRT_Ik": {
    "tags": [
      "relationships"
    ]
  },
  "GGEqE3UxKLU": {
    "tags": [
      "relationships"
    ]
  },
  "ZdITbvPxkjM": {
    "tags": [
      "relationships"
    ]
  },
  "E6acNMU8Vx8": {
    "tags": [
      "relationships"
    ]
  },
  "mfzv3iEiKzw": {
    "tags": [
      "relationships"
    ]
  },
  "WlulnTT3e-k": {
    "tags": [
      "relationships"
    ]
  },
  "uI4VMqMVMl4": {
    "tags": [
      "relationships"
    ]
  },
  "vStlPMAxG1U": {
    "tags": [
      "relationships",
      "ai"
    ]
  },
  "hrM6rDtS5mQ": {
    "tags": [
      "relationships"
    ]
  },
  "WavOLvmCq1s": {
    "tags": [
      "relationships"
    ]
  },
  "RgayDO3d9c0": {
    "tags": [
      "relationships"
    ]
  },
  "OQwvE67eTM0": {
    "tags": [
      "relationships"
    ]
  },
  "fPQAiyJv-vg": {
    "tags": [
      "relationships"
    ]
  },
  "w_vtx75zc-8": {
    "tags": [
      "relationships"
    ]
  },
  "ZorTrgiAOdI": {
    "tags": [
      "relationships"
    ]
  }
};
