import { prisma } from "../src/lib/db";
import * as fs from "fs";
import * as path from "path";

// Remove local prisma init
// const prisma = new PrismaClient();

const KEYWORD_MAP: Record<string, string[]> = {
  ai: ["ai", "gpt", "llm", "openai", "midjourney", "neural", "intelligence", "machine learning", "automation"],
  coding: ["coding", "code", "programming", "software", "developer", "javascript", "react", "nextjs", "python", "tutorial"],
  apple: ["iphone", "apple", "macbook", "ipad", "ios", "vision pro", "m3", "m4"],
  gadgets: ["gadget", "unboxing", "review", "pixel", "samsung", "tech", "hardware"],
  finance: ["finance", "money", "investing", "stock", "crypto", "bitcoin", "business", "market", "economy"],
  fitness: ["gym", "workout", "yoga", "fitness", "bodybuilding", "exercise", "training", "diet", "muscle"],
  lifestyle: ["vlog", "routine", "day in life", "productivity", "habit", "motivation"],
  gaming: ["gaming", "game", "ps5", "xbox", "nintendo", "playstation", "streaming", "gameplay", "fps", "rpg"],
  photography: ["photo", "photography", "camera", "sony", "canon", "cinematic", "lens", "video"],
  food: ["cooking", "recipe", "food", "chef", "delicious", "eat", "dinner", "cake", "recipe", "restaurant"],
  art: ["art", "painting", "drawing", "watercolor", "artist", "creative", "design", "sculpture"],
  music: ["music", "song", "performance", "concert", "singer", "official video", "beat", "cover"],
  science: ["science", "space", "physics", "universe", "nasa", "discovery", "nature", "earth"],
  fashion: ["fashion", "style", "outfit", "clothing", "brand", "model", "streetwear"],
};

async function main() {
  console.log("🚀 Scanning database to generate extra-metadata.ts...");
  
  const items = await prisma.clusterItem.findMany({
    select: {
      id: true,
      title: true,
      description: true,
      clusterId: true,
    }
  });

  const metadata: Record<string, { tags: string[] }> = {};

  for (const item of items) {
    const tags = new Set<string>();
    
    // Add cluster as a base tag
    const clusterTag = item.clusterId.replace("region-", "");
    tags.add(clusterTag);

    // Scan title and description for keywords
    const content = (item.title + " " + item.description).toLowerCase();
    
    for (const [tag, keywords] of Object.entries(KEYWORD_MAP)) {
      if (keywords.some(k => content.includes(keywords[0]))) { // Simplified matching
         if (keywords.some(k => content.includes(k))) {
            tags.add(tag);
         }
      }
    }

    metadata[item.id] = {
      tags: Array.from(tags).slice(0, 3) // Limit to 3 tags
    };
  }

  const outputPath = path.join(process.cwd(), "src/lib/feed/extra-metadata.ts");
  const content = `// This file is auto-generated by scripts/generate-extra-metadata.ts
// Do not edit manually.

export const EXTRA_METADATA: Record<string, { tags: string[] }> = ${JSON.stringify(metadata, null, 2)};
`;

  fs.writeFileSync(outputPath, content);
  console.log(`✅ Generated metadata for ${items.length} items at ${outputPath}`);
}

main()
  .catch(e => console.error(e))
  .finally(async () => await prisma.$disconnect());
